./gradlew NeuralBot:publishToMavenLocal
./gradlew MallorcaNeural:publishToMavenLocal
./gradlew Tools:publishToMavenLocal
./gradlew MallorcaCore:publishToMavenLocal
./gradlew MallorcaBrains:publishToMavenLocal
./gradlew Neuroph:publishToMavenLocal
./gradlew GamePresenter:publishToMavenLocal
./gradlew AdviceCreator:publishToMavenLocal
./gradlew MallorcaEquilator:publishToMavenLocal
